### ISSUE TITLE
Issues on Fedora22

### ISSUE THREAD

**Issue by Jmainguy** [abutcher/juicer#15]
After getting it compiled and such for virtualenv

```
(juicerenv)[jmainguy@Jmainguy-Fedora ~]$ juicer hello
Traceback (most recent call last):
  File "/home/rdu/jmainguy/juicer/juicerenv/bin/juicer", line 9, in <module>
    load_entry_point('juicer==1.0.0', 'console_scripts', 'juicer')()
  File "/home/rdu/jmainguy/juicer/juicerenv/lib/python2.7/site-packages/juicer/parser/Parser.py", line 548, in main
    args.cmd(args).run()
  File "/home/rdu/jmainguy/juicer/juicerenv/lib/python2.7/site-packages/juicer/command/hello.py", line 28, in run
    pulp = juicer.pulp.Pulp(self.connections[environment])
KeyError: 're'
```

```
[jmainguy@Jmainguy-Fedora ~]$ cat .config/juicer/config
[DEFAULT]
username: admin
password: admin
port: 4443
verify_ssl: False
start_in: devel
cart_seeds: localhost:27017
ca_path: /etc/pki/pulp/ca.crt
cert_filename: /etc/pki/pulp/pulp.crt

[devel]
hostname: pulp.soh.re
```

**Comment by abutcher** [comment]
@Jmainguy Give that a try.

**Comment by Jmainguy** [comment]
@abutcher++ like a charm

```
(juicerenv)[jmainguy@Jmainguy-Fedora juicer]$ juicer hello
sohre: pulp.soh.re OK
```

**Comment by abutcher** [comment]
Beauty! Thanks for the heads up @Jmainguy
