### ISSUE TITLE
Where do I get a list of distribitors?

### ISSUE THREAD

**Issue by Jmainguy** [abutcher/juicer#16]
Hey,

I am trying to add iso as a repo type,

{'distributor_id': 'iso_web_distributor_name_cli'} is what I guessed it was called, I added it to types.py

when trying to create it though I get this error.

```
(juicerenv)[jmainguy@Jmainguy-Fedora juicer]$ juicer repo create test -t iso
Traceback (most recent call last):
  File "/home/rdu/jmainguy/juicer/juicerenv/bin/juicer", line 9, in <module>
    load_entry_point('juicer==1.0.0', 'console_scripts', 'juicer')()
  File "/home/rdu/jmainguy/juicer/juicerenv/lib/python2.7/site-packages/juicer/parser/Parser.py", line 549, in main
    args.cmd(args).run()
  File "/home/rdu/jmainguy/juicer/juicerenv/lib/python2.7/site-packages/juicer/command/repo.py", line 32, in run
    checksumtype=self.args.checksum_type)
  File "/home/rdu/jmainguy/juicer/juicerenv/lib/python2.7/site-packages/juicer/pulp/__init__.py", line 93, in create
    id=repo_data['id'],
UnboundLocalError: local variable 'repo_data' referenced before assignment
```

Is there another file I need to edit, or did I just guess the distributor wrong?

xmpp = jon@soh.re
irc = freednode/jmainguy

**Comment by abutcher** [comment]
curl -vk -u '<USER>:<PASS>' https://<HOST>/pulp/api/v2/plugins/distributors/

**Comment by Jmainguy** [comment]
Ty sir
