### ISSUE TITLE
Running `juicer repo show REPO` on a newly created repo errors on showing rpm count

### ISSUE THREAD

**Issue by abutcher** [abutcher/juicer#7]
Maybe don't show the content counts unless it is more generic for any kind of units OR not at all.

```
$ juicer repo show test-repo
re
  name: test-repo
Traceback (most recent call last):
  File "/home/abutcher/juicer/juicerenv/bin/juicer", line 9, in <module>
    load_entry_point('juicer==1.0.0', 'console_scripts', 'juicer')()
  File "/home/abutcher/juicer/juicerenv/lib/python2.7/site-packages/juicer/parser/Parser.py", line 582, in main
    args.cmd(args).run()
  File "/home/abutcher/juicer/juicerenv/lib/python2.7/site-packages/juicer/command/repo/RepoShowCommand.py", line 32, in run
    json=self.args.json)
  File "/home/abutcher/juicer/juicerenv/lib/python2.7/site-packages/juicer/pulp/Repo.py", line 125, in show
    self.output.info("  rpms: {0}".format(repo['content_unit_counts']['rpm']))
KeyError: 'rpm'
```

**Comment by hzgraham** [comment]
I'm thinking it is erroring because 'rpm' is empty. We just need to add a conditional or something
